services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: toortoor
    ports:
      - "0:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    image: tomcat:latest
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend